id: jade
node:
  number: 1
gpu:
  present: True
  min: 0
  max: 8
  type: DGX-1
cpu:
  cores: 40
  simd: AVX2_256
  threads: True
gromacs:
  version: "2018.3"
  command: |-
    #!/bin/bash
    #SBATCH --nodes=NTNODES
    #SBATCH --ntasks-per-node=NTMPI
    #SBATCH --cpus-per-task=NTOMP
    #SBATCH --gres=gpu:NTMPI
    #SBATCH --gres-flags=enforce-binding
    #SBATCH --time=00:13:00
    #SBATCH -J TPRFILE
    #SBATCH -p big

    module purge
    module load gromacs/2018.3

    cp TPRFILEPATH TPRFILE.tpr

    mpirun -np ${SLURM_NTASKS_PER_NODE} --bind-to socket mdrun_mpi -deffnm TPRFILE -maxh 0.2 -resethway -noconfout -ntomp ${SLURM_CPUS_PER_TASK} &> TPRFILE.log
