id: lambda
node:
  number: 1
gpu:
  present: False
cpu:
  cores: 12
  simd: AVX2_256
  threads: False
gromacs:
  version: "2016.4"
  command: |-
    #! /bin/bash

    source /usr/local/gromacs/2016.4/bin/GMXRC

    cp TPRFILEPATH TPRFILE.tpr

    mpirun -np NTMPI mdrun_mpi -deffnm TPRFILE -ntomp NTOMP -resethway -maxh 0.1 -noconfout -pin on
